# Generated by Django 4.1 on 2023-07-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_game_alter_product_options_remove_product_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boolparamsforproducts',
            options={'verbose_name': 'Есть/нет параметр', 'verbose_name_plural': 'Есть/нет параметры'},
        ),
        migrations.AlterModelOptions(
            name='gameonsteam',
            options={'ordering': ('id',), 'verbose_name_plural': 'Игры на аккаунте'},
        ),
        migrations.AlterModelOptions(
            name='pifparamsforproducts',
            options={'verbose_name_plural': 'Кол-во подписчиков, баланса - больших значений'},
        ),
        migrations.AlterModelOptions(
            name='psifparamsforproducts',
            options={'verbose_name_plural': 'Кол-во чатов, групп - небольших значений'},
        ),
        migrations.AlterField(
            model_name='gameonsteam',
            name='balance',
            field=models.PositiveSmallIntegerField(help_text='укажите примерную стоимость внутриигровых предметов', verbose_name='Стоимость игрового инвентаря:'),
        ),
        migrations.AlterUniqueTogether(
            name='boolparamsforproducts',
            unique_together={('name', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='gameonsteam',
            unique_together={('acc', 'game')},
        ),
        migrations.AlterUniqueTogether(
            name='pifparamsforproducts',
            unique_together={('name', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='psifparamsforproducts',
            unique_together={('name', 'product')},
        ),
    ]
