# Generated by Django 4.1 on 2023-07-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_boolparamsforproducts_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boolparamsforproducts',
            old_name='active',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='pifparamsforproducts',
            old_name='active',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='psifparamsforproducts',
            old_name='active',
            new_name='value',
        ),
    ]
