# Generated by Django 4.1 on 2023-08-01 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_active_boolparamsforproducts_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SexParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('man', 'Мужской'), ('woman', 'Женский')], max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sex', to='shop.product')),
            ],
            options={
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='PhoneCountryParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('RU', 'Россия'), ('US', 'США'), ('KZ', 'Казахстан')], max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_country', to='shop.product')),
            ],
            options={
                'verbose_name': 'Страна номера',
                'verbose_name_plural': 'Страна номера',
            },
        ),
        migrations.CreateModel(
            name='EmailDomainParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('yandex', '@yandex'), ('gmail', '@gmail'), ('rambler', '@rambler'), ('mail', '@mail')], help_text='выберите нужный почтовый домен', max_length=200, verbose_name='Домен:')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain', to='shop.product')),
            ],
            options={
                'verbose_name': 'Домен',
                'verbose_name_plural': 'Почтовый домен',
            },
        ),
    ]
