# Generated by Django 4.1 on 2023-08-01 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_sexparam_phonecountryparam_emaildomainparam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boolparamsforproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bools', to='shop.product'),
        ),
    ]
