# Generated by Django 4.1 on 2023-08-01 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_boolparamsforproducts_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonecountryparam',
            options={'verbose_name': 'Регион номера', 'verbose_name_plural': 'Регион номера'},
        ),
        migrations.AlterField(
            model_name='boolparamsforproducts',
            name='name',
            field=models.CharField(choices=[('premium', 'Премиум'), ('spam_block', 'Спам блок'), ('password', 'Пароль'), ('cookies', 'Куки'), ('binding_phone', 'Привязка к телефону')], help_text='выберите параметр', max_length=200, verbose_name='Параметр:'),
        ),
        migrations.AlterField(
            model_name='phonecountryparam',
            name='value',
            field=models.CharField(choices=[('RU', 'Россия'), ('US', 'США'), ('KZ', 'Казахстан')], help_text='выберите регион номера телефона', max_length=200, verbose_name='Регион:'),
        ),
        migrations.AlterField(
            model_name='pifparamsforproducts',
            name='name',
            field=models.CharField(choices=[('chat_subs', 'Кол-во подписчиков в чатах'), ('general_balance', 'Баланс на аккаунте'), ('subs', 'Кол-во Подписчиков'), ('votes', 'Кол-во голосов')], help_text='выберите параметр', max_length=200, verbose_name='Параметр:'),
        ),
        migrations.AlterField(
            model_name='sexparam',
            name='value',
            field=models.CharField(choices=[('man', 'Мужской'), ('woman', 'Женский')], help_text='выберите подходящее значение', max_length=200, verbose_name='Пол:'),
        ),
        migrations.CreateModel(
            name='EmailAccessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('AUTO', 'Авторег'), ('ORIGINAL', 'Родная'), ('NO', 'Без почты')], max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_access', to='shop.product')),
            ],
            options={
                'verbose_name_plural': 'Доступ к почте',
            },
        ),
    ]
