# Generated by Django 4.1 on 2023-08-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_phonecountryparam_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='message_to_customer',
            field=models.TextField(default=1, help_text='это сообщение увидит покупатель после покупки', max_length=200, verbose_name='Сообщение покупателю после покупки:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='укажите краткое описание продовамеого/ых аккаунта/ов.', max_length=200, verbose_name='Описание:'),
        ),
    ]
