# Generated by Django 4.1 on 2023-08-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_message_to_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='login',
            field=models.CharField(default=1, help_text='укажите логин или аналогичные данные для входа', max_length=200, verbose_name='Логин:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='password',
            field=models.CharField(default=1, help_text='укажите пароль от аккаунта', max_length=200, verbose_name='Пароль:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='token',
            field=models.CharField(default=1, help_text='укажите токен авторизации или аналогичные данные', max_length=200, verbose_name='Токен авторизации:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sexparam',
            name='value',
            field=models.CharField(choices=[('man', 'Мужской'), ('woman', 'Женский'), (None, 'Неизвестно')], help_text='выберите подходящее значение', max_length=200, verbose_name='Пол:'),
        ),
    ]
