# Generated by Django 4.1 on 2023-07-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(help_text='выберите, чтобы сделать ее активной.изменения применятся, если нет другой активнойрекламы', unique=True, verbose_name='Показывать рекламу:')),
                ('banner', models.ImageField(help_text='выберите рекламный баннер', upload_to='media/adv/', verbose_name='Баннер:')),
                ('name', models.CharField(help_text='укажите название компании/заказчика', max_length=200, verbose_name='Название:')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
                'ordering': ('active',),
            },
        ),
    ]
