# Generated by Django 4.1 on 2023-07-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ('-active',), 'verbose_name': 'Реклама', 'verbose_name_plural': 'Рекламы'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='link',
            field=models.CharField(default=12, help_text='вставьте ссылку для рекламной компании', max_length=100000, verbose_name='Реферальная ссылка:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='active',
            field=models.BooleanField(help_text='выберите, чтобы сделать ее активной. Изменения применятся, если нет другой активной рекламы', unique=True, verbose_name='Показывать рекламу:'),
        ),
    ]
